---
title: "figures"
author: "Courtney B. Hilton"
date: "11/04/2022"
output: pdf_document
---

```{r rmd_config, include = FALSE}

# chunk options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# prevent scientific notation for numerals
options(scipen = 999)

```

```{r libraries}

library(pacman)
p_load(
  broom,
  knitr,
  ggridges,
  ggtext,
  scales,
  lmerTest,
  broom.mixed,
  patchwork,
  gghighlight,
  kableExtra,
  ggrepel,
  jtools, 
  here,
  tidyverse,
  survey,
  ggeffects,
  emmeans,
  meta
)

color_scheme <- c("#85C0F9", "#A95AA1", "#F5793A")

# save figure outputs here
knitr::opts_chunk$set(fig.path = here("viz", "figures", ""), dpi = 500)

load(here("results", "analyses.RData"))
load(here("results", "meta_analyses.RData"))
load(here("results", "permutation_tests.RData"))
miq_combined_filtered <- read.csv(here("data", "Combined", "Combined_filtered.csv"))

```


```{r Figure2, fig.width = 12, fig.height = 6}

size_dat <- miq_combined_filtered %>%
  count(language) %>%
  mutate(
    language = case_when(
      language == "Chinese/Mandarin" ~ "Mandarin",
      language == "Chinese/Cantonese/Yue" ~ "Cantonese",
      language == "Chinese/Taiwanese/Min Nan/Hokkien" ~ "Hokkien",
      language == "Chinese/Other dialects" ~ "Other Chinese Dialects",
      TRUE ~ language
    )
  ) %>%
  full_join(., languages %>%
              mutate(
                language = case_when(
                  language == "Chinese/Mandarin" ~ "Mandarin",
                  language == "Chinese/Cantonese/Yue" ~ "Cantonese",
                  language == "Chinese/Taiwanese/Min Nan/Hokkien" ~ "Hokkien",
                  TRUE ~ language
                )
              )) %>%
  mutate(Tone = ifelse(is.na(Tone), "Tonal", Tone)) %>% # all NAs are the additional rarer tonal languages
  select(language, n, Tone)

set.seed(10)

p1 <- size_dat %>%
  filter(n > 500) %>%
  ggplot() +
  theme_apa() +
  geom_text_repel(
    aes(
      label = language,
      x = Tone,
      y = n,
      color = Tone,
      size = n
    ),
    min.segment.length = 999, # removing segments
    position = position_jitter(width = 0.3),
    max.overlaps = 50
  ) +
  scale_color_manual(values=color_scheme)+
  scale_y_log10(labels = comma) +
  scale_x_discrete(labels = c(
    "<i style='color:#85C0F9;'>Non-tonal</i>",
    "<i style='color:#A95AA1;'>Pitch-accented</i>",
    "<i style='color:#F5793A;'>Tonal</i>"),
    name = NULL) +
  scale_size(range = c(4, 20), name = "Sample Size") +
  theme(
    axis.title.y = element_text(size = 20),
    axis.text.x = element_markdown(size = 16, face = "bold"),
    axis.text.y = element_text(size = 16),
    legend.position = "none",
    plot.margin = margin(1,200,1,1)
  ) +
  labs(y = "Sample Size", x = "Language Type", color = "Language Type") + 
  # annotate("text", x = 4, y = 1000, label = "fuck") + 
  coord_cartesian(clip = "off") +
  geom_curve(x = 3, xend = 3.9, y = 2.9, yend = 3.5, curvature = 0, arrow = arrow(length = unit(0.03, "npc")), colour = "black", size = .5) + 
  geom_rect(xmin = 2.9, ymin = 2.9, xmax = 3, ymax = 3, colour = "black", alpha = 0)


set.seed(57)
p2 <- size_dat %>%
  filter(n < 500) %>%
  ggplot() +
  theme_apa() +
  geom_text_repel(
    aes(
      label = language,
      x = Tone,
      y = n,
      color = Tone,
      size = n
    ),
    min.segment.length = 999, # removing segments
    position = position_jitter(width = 0.3)
  ) +
  scale_color_manual(values="#F5793A") +
  scale_y_log10(labels = comma, n.breaks = 7) +
  scale_x_discrete(labels = c("<i style='color:#F5793A;'>Tonal</i>"),
    name = NULL) +
  labs(
    y = NULL
  ) +
  scale_size(range = c(3, 6), name = "Sample Size") +
  theme(
    axis.title.y = element_text(size = 20),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 16),
    legend.position = "none"
  )


p1 + inset_element(p2, left = 1.01, bottom = 0.3, right = 1.35, top = .9)


```

```{r Figure3, fig.width = 10, fig.height = 4}

test <- mods$total_mix_full$mdt$marginal %>% 
  bind_rows(., mods$total_mix_full$mpt$marginal) %>% 
  bind_rows(., mods$total_mix_full$cabat$marginal) 

mods$total_mix_full$mdt$marginal %>% 
  bind_rows(., mods$total_mix_full$mpt$marginal) %>% 
  bind_rows(., mods$total_mix_full$cabat$marginal) %>% 
  pivot_wider(names_from = group, values_from = c(predicted:conf.high)) %>% 
  mutate(tone = factor(x, levels = c("Non-tonal", "Pitch-accented", "Tonal")),
         test = factor(test, levels = c("mdt", "mpt", "cabat"))) %>% 
  ggplot(.,
         aes(x = test, y = predicted_No, color = tone)) +
  geom_hline(aes(yintercept = 0), color = "black", alpha = 0.7, linetype = "dashed") +
  geom_errorbar(aes(ymax = conf.high_No, ymin = conf.low_No, color = tone), position = position_dodge(.5), width = .2, key_glyph = draw_key_rect) +
  geom_errorbar(aes(ymax = conf.high_Yes, ymin = conf.low_Yes, color = tone), position = position_dodge(.5), width = .2, alpha = .5, key_glyph = draw_key_rect) +
  geom_point(position = position_dodge(.5), size = 2) +
  geom_point(data = test, aes(x = test, y = predicted, shape = group), inherit.aes = FALSE, alpha = 0) +
  scale_shape_manual(values = c(19, 17), name = "test",
                     labels = c("Without Music Lessons", "With Music Lessons")) +
  geom_point(aes(y = predicted_Yes), position = position_dodge(.5), size = 2, alpha = .5, pch = 17) +
  geom_linerange(aes(ymax = predicted_Yes, ymin = predicted_No, color = tone), position = position_dodge(.5), linetype = "dashed", alpha = .5) +
  scale_x_discrete(labels = c("Melodic Discrimination","Mistuning Perception", "Beat Alignment"), position = "top") +
  scale_color_manual(values=color_scheme, labels = c("Non-tonal","Pitch-accented","Tonal")) +
  guides(shape = guide_legend(override.aes = list(alpha = .8, size = 4))) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.text.x = element_text(size = 16),
    panel.grid.major.y = element_line(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    legend.position = "bottom",
    legend.text = element_text(size = 12))

```


```{r Figure4, fig.width = 21.2, fig.height = 15, out.extra='angle=90', out.width="100%", out.height="100%"}

lang_counts <- miq_combined_filtered |> count(language)

lang_plotter2 <- function(data, x_lab, y_lab = NULL) {
  ggplot(data, aes(x = estimate, y = language, xmin = conf.low, xmax = conf.high, colour = Tone)) +
    geom_vline(xintercept = 0, lty = "dashed", colour = "grey50") + 
    geom_point(size = 2) +
    geom_errorbar(size = 1) +
    scale_colour_manual(values = c("#85C0F9", "#A95AA1", "#F5793A"),
                        labels = c("Non-tonal","Pitch-accented", "Tonal"),
                        name = "Language type") +
    lims(x = c(-0.9,0.9)) +
    labs(
      x = NULL,
      y = NULL, 
      title = x_lab
    ) +
    geom_text(aes(label = lang_label, x = conf.high + 0.1), colour = "black", hjust = 0, size = 6) +
    theme_minimal() +
    guides(colour = guide_legend(override.aes = list(size=10))) +
    coord_cartesian(clip = "off") +
    theme(axis.text.y= element_blank(),
          axis.title = element_text(size = 30),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = 16),
          legend.text = element_text(size = 22),
          legend.title = element_text(size = 24, hjust = 0.5),
          panel.grid = element_blank(),
          plot.title = element_text(hjust = 0.5, size = 24),
    ) 
}

format_language_label <- function(data, add_count = FALSE) {
  data <- data |> 
    mutate(level_clean = case_when(
      level == "Chinese/Mandarin" ~ "Mandarin",
      level == "Chinese/Cantonese/Yue" ~ "Cantonese",
      level == "Chinese/Other languages" ~ "Other Chinese languages",
      level == "Chinese/Taiwanese/Min Nan/Hokkien" ~ "Hokkien",
      TRUE ~ level
    ))
  
  if (add_count) {
    output <- data |>
    left_join(lang_counts, by = c("level" = "language")) |>
    mutate(n = as.integer(n)) |>
    mutate(lang_label = paste0(level_clean, " (", str_trim(format(n, big.mark = ",")), ")"))
  } else {
    output <- data |> 
      mutate(lang_label = level_clean)
  }
  return(output)
}

p1 <- lang_plotter2(format_language_label(mods$languages$mdt, TRUE), "Melodic Discrimination")
p2 <- lang_plotter2(format_language_label(mods$languages$mpt, TRUE), "Mistuning Perception")
p3 <- lang_plotter2(format_language_label(mods$languages$cabat, TRUE), "Beat Alignment")

p1+p2+p3 +
  plot_layout(guides = "collect") &
  theme(legend.position = "right")

```


\clearpage
```{r FigureS1, fig.height=3, fig.width=6}
headphone_score <- read.csv(here("data", "headphone_score.csv"))

ggplot(headphone_score) +
  geom_bar(aes(score), colour = "black", fill = "grey20") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = 0:6, breaks = 0:6) +
  geom_vline(aes(xintercept = mean(score)), color = "red", linetype = "longdash", size = 1.5) +
  labs(
    y = "Participant Count",
    x = "Headphone Test Score"
  ) +
  theme_minimal()

```


```{r meta-analysis-fig-functions}

r2 <- function(num) {format(round(num, 2), nsmall = 2)}

forest_plot_creator <- function (left_side_data, ci_sep = " to ",
                                 right_side_data = NULL, estimate_precision = 1, ggplot_width = 30, 
                                 file_path, dpi = 600, display = TRUE, font_family = "sans", 
                                 estimate_col_name = "Estimate", stripe_colour = "white", 
                                 background_colour = "white", nudge_y = 0, nudge_x = 1, nudge_height = 0, 
                                 nudge_width = 0, justify = 0, center_ggplot, render_as = "pdf",
                                 left_offset = 0, right_offset = 0, top_offset = 0, bottom_offset = 0) {
  
  # define table theme
  theme <- gridExtra::ttheme_minimal(
    core = list(
      fg_params = list(
        hjust = justify,
        x = (0.05 + (0.45/0.5) * justify),
        fontfamily = font_family
      ), 
      bg_params = list(
        fill = c(rep(c(stripe_colour, background_colour), length.out = nrow(left_side_data)),background_colour,background_colour, background_colour)
      )
    ), 
    colhead = list(
      fg_params = list(
        hjust = 0,
        x = 0.05,
        fontfamily = font_family,
        cex = 1.2
      ),
      bg_params = list(fill = background_colour)
    )
  )
  
  # plot data
  # gdata <- data.frame(estimate = estimate, ci_low = ci_low, ci_high = ci_high)
  
  if (is.null(right_side_data)) {
    tdata <- gdata
    tdata <- dplyr::mutate_all(tdata, ~sprintf(., fmt = paste0("%#.", 
                                                               estimate_precision, "f")))
    tdata[tdata == "NA"] <- " "
    right_side_data <- data.frame(Estimate = ifelse(tdata$estimate == 
                                                      " ", " ", paste0(tdata$estimate, " (", tdata$ci_low, 
                                                                       ci_sep, tdata$ci_high, ")")))
    colnames(right_side_data) <- estimate_col_name
  }
  
  # function to find width of table data
  find_width <- function(data) {
    num_of_rows <- nrow(data)
    num_of_cols <- ncol(data)
    print_data <- dplyr::mutate_all(data, as.character)
    width <- 0
    names <- colnames(print_data)
    for (i in 1:num_of_cols) {
      temp <- systemfonts::shape_string(print_data[[names[i]]], 
                                        family = font_family)
      temp_col <- systemfonts::shape_string(names[i], family = font_family)
      width[i] <- max(max(temp$metrics$width, na.rm = TRUE), 
                      temp_col$metrics$width, na.rm = TRUE)
    }
    return(sum(width, na.rm = TRUE)/7.2)
  }
  
  # Compute width of left side data
  left_width <- find_width(left_side_data)
  right_width <- find_width(right_side_data)
  
  # Compute total width
  total_width <- left_width + right_width + ggplot_width
  tdata_print <- left_side_data
  
  # add blank section where ggplot will go
  tdata_print$` ` <- paste(rep(" ", times = round(ggplot_width, 0)), collapse = "")
  
  # combine with right-side data
  tdata_print <- cbind(tdata_print, right_side_data)
  
  tdata_print <- tdata_print |> 
    dplyr::mutate_all(as.character) |> # force all to character
    dplyr::mutate_all(replace_na, " ") # make NAs blank
  
  
  mono_column <- function(table, col) {
    col_indexes <- function(table, col, name = "core-fg") {
      l <- table$layout
      which(l$l == col & l$name == name)
    }
    ind <- col_indexes(table, col, "core-fg")
    for (i in ind) {
      table$grobs[i][[1]][["gp"]] <- grid::gpar(fontfamily = "mono")
    }
    return(table)
  }
  
  png_width <- total_width/10 + nudge_x
  png_height <- (nrow(tdata_print) + 3)/3.8
  
  table_final <- mono_column(gridExtra::tableGrob(tdata_print, theme = theme, rows = NULL), ncol(left_side_data) + 1)
  
  # set plot column to correct width
  table_final$widths[ncol(left_side_data) + 1] <- grid::unit(ggplot_width/10, "in")
  table_final$heights <- grid::unit(rep(0.255, times = length(table_final$heights)), "in")
  
  final <- patchwork::wrap_elements(table_final) + patchwork::inset_element(
    center_ggplot, 
    align_to = "full", 
    left = (left_width/total_width) + left_offset, 
    right = ((ggplot_width + left_width)/total_width) + right_offset, 
    top = 0.9 + top_offset, 
    bottom = 0.35/nrow(tdata_print) + bottom_offset
  )
  
  if (!(render_as == "rmarkdown")) {
    ggplot2::ggsave(final, dpi = dpi, height = png_height + nudge_height, 
                    width = png_width + nudge_width, units = "in", filename = file_path, 
                    device = render_as)
    if (display == TRUE) {
      system(paste0("open \"", file_path, "\""))
    }
  }
  else {
    final
  }
}

clean_data_for_table <- function(meta_data, dataname, add_rows = FALSE) {
  out <- bind_cols(meta_data$clean, as_tibble(meta_data)) |> 
    select(
      Study, Measure, `Tonal Sample` = Tonal, `Non-tonal Sample` = `Non-tonal`, TE, SMD = hedge_g, lower, upper, w.random
    ) |> 
    mutate(Power = scales::percent(meta_data$Power, scale = 100, accuracy = 1L), .before = TE) |> 
    mutate(
      Estimate = r2(TE), 
      across(c(lower, upper), r2, .names = "{.col}_clean"),
      `95% CI` = str_c("[", lower_clean, ", ", upper_clean, "]"),
      Estimate = str_c(Estimate, " ", `95% CI`),
      overall = meta_data$TE.random,
      Weight = scales::percent(weights(meta_data)$p.random, scale = 1, accuracy = 1L),
      Study = str_remove_all(Study, "\\\\") # remove escape characters
    ) |>
    arrange(desc(TE)) |> 
    bind_rows(tibble(TE = meta_data$TE.random, Study = "Overall")) |> 
    # add a couple blank rows at the end
    mutate(dataname = dataname)
  
  if (add_rows) {
    out <- out |> 
      add_row() |> add_row()
  }
  
  return(out)
}

meta_plotter <- function(meta_data) {
  fixed_effect <- meta_data |> filter(Study == "Overall") |> pull(TE)
  
  meta_data |> 
    mutate(
      Study = str_c(Study, str_replace_na(Measure, "")),
      Study = fct_reorder(Study, TE),
      Study = fct_relevel(Study, "Overall", after = 0),
      overall = ifelse(Study == "Overall", "1", "0")
    ) |>
    ggplot(aes(y = Study, x = TE, xmin = lower, xmax = upper,
               shape = overall, size = overall)) + 
    geom_vline(xintercept = fixed_effect, lty = "dotted", alpha = 0.6) +
    geom_vline(xintercept = 0) +
    geom_point() +
    geom_errorbar(size = 0.6) +
    scale_shape_manual(values = c(19,5)) +
    scale_size_manual(values = c(2, 5)) +
    theme_classic() + 
    theme(
      legend.position = "none",
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.x = element_blank()
    )
}

meta_fig_assembler <- function(meta_data, dataname, filename, left_offset = 0, right_offset = 0, top_offset = 0, bottom_offset = 0) {
  tab_data <- clean_data_for_table(meta_data, dataname)
  center_plot <- meta_plotter(tab_data)
  
  forest_plot_creator(left_side_data = select(tab_data, 1:5) |> mutate(Study = ifelse(Study == "Overall", " ",Study)),
                      right_side_data = select(tab_data, Estimate, Weight),
                      center_ggplot = center_plot,
                      top_offset = top_offset,
                      bottom_offset = bottom_offset,
                      left_offset = left_offset,
                      right_offset = right_offset,
                      file_path = here("viz", "temp", filename))
}

meta_plotter_combined <- function(data) {
  dat <- data |> 
    group_by(Study) |>
    mutate(Study = str_c(Study, row_number())) |>
    ungroup() |> 
    mutate(
      Study = fct_inorder(Study) |> fct_rev(),
      plot_order = as.numeric(Study),
      plot_order = case_when(
        # adding the vertical offsets in the plots to match the table
        dataname == "melodic" ~ plot_order + 6,
        dataname == "pitch" ~ plot_order + 3,
        TRUE ~ plot_order
      )
    ) |> 
    arrange(-row_number()) |> 
    mutate(row = row_number())
  
  melodic_effect <- filter(dat, Study == "Overall1") |> pull(TE)
  pitch_effect <- filter(dat, Study == "Overall2") |> pull(TE)
  rhythm_effect <- filter(dat, Study == "Overall3") |> pull(TE)
  
  ggplot(dat, aes(y = row, x = TE, xmin = lower, xmax = upper,
                         shape = overall, size = overall, stroke = overall, colour = overall)) + 
    # create vertical line annotation to indicate fixed effects
    annotate("segment", x = melodic_effect, xend = melodic_effect, y = 34.5, yend = 46.5, lty = "dotted") +
    annotate("segment", x = pitch_effect, xend = pitch_effect, y = 11.5, yend = 31.5, lty = "dotted") +
    annotate("segment", x = rhythm_effect, xend = rhythm_effect, y = 1.5, yend = 8.5, lty = "dotted") +
    # add text annotation for the fixed effects
    annotate("text", x = melodic_effect + 0.67, xend = melodic_effect + 0.67, y = 35, yend = 35, label = r2(melodic_effect)) +
    annotate("text", x = pitch_effect + 0.67, xend = pitch_effect + 0.67, y = 11, yend = 11, label = r2(pitch_effect)) +
    annotate("text", x = rhythm_effect + 0.72, xend = rhythm_effect + 0.72, y = 1, yend = 1, label = r2(rhythm_effect)) +
    geom_vline(xintercept = 0) +
    geom_point() +
    geom_errorbar(size = 0.6) +
    scale_colour_manual(values = c("grey50", "black")) +
    scale_discrete_manual(aesthetics = "stroke", values = c(0.8, 1.5)) +
    scale_shape_manual(values = c(19,5)) +
    scale_size_manual(values = c(2, 5)) +
    coord_cartesian(ylim = c(1.75, 46)) +
    theme_classic() + 
    theme(
      legend.position = "none",
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.x = element_blank()
    )
}

clean_for_plotting <- function(data) {
  data |> 
    mutate(
      Study = str_c(Study, str_replace_na(Measure, "")),
      Study = fct_reorder(Study, TE),
      Study = fct_relevel(Study, "Overall", after = 0),
      overall = ifelse(Study == "Overall", "1", "0")
    ) 
}


meta_fig_assembler2 <- function(meta_data1, meta_data2, meta_data3, filename,
                                left_offset = 0, right_offset = 0, top_offset = 0, bottom_offset = 0) {
  tab_data1 <- clean_data_for_table(meta_data1, "melodic", TRUE)
  tab_data2 <- clean_data_for_table(meta_data2, "pitch", TRUE)
  tab_data3 <- clean_data_for_table(meta_data3, "rhythm", FALSE)
  center_plot <- bind_rows(
    tab_data1 |> clean_for_plotting(),
    tab_data2 |> clean_for_plotting(),
    tab_data3 |> clean_for_plotting()
  ) |> 
    meta_plotter_combined()
  
  combined <- bind_rows(tab_data1, tab_data2, tab_data3)
  
  forest_plot_creator(left_side_data = select(combined, 1:5) |> mutate(Study = ifelse(Study == "Overall", " ",Study)),
                      right_side_data = select(combined, Estimate, Weight),
                      center_ggplot = center_plot,
                      top_offset = top_offset,
                      bottom_offset = bottom_offset,
                      left_offset = left_offset,
                      right_offset = right_offset,
                      file_path = here::here("viz", "figures", filename))
}

```



```{r}
# cleaning the meta-analysis data

# MDT
melodic.gen.random$clean <- melodic.gen.random$data |> 
  mutate( 
    Tonal = str_c(Tonal_N, " (", Non_CM_tonal, ")"), 
    `Non-tonal` = str_c(Non_tonal_N, " (", Non_E_nontonal, ")"),
    Measure = if_else(Measure == "Interval discrimination/Musical Task", "Interval discrimination", Measure),
    Tonal = case_when(
      Study == "Peretz et al. (2011)" ~ "18 Mandarin; 4 Vietnamese; 2 Cantonese",
      Study == "Zheng \\& Samuel (2018)" ~ "24 Mandarin",
      Study == "Stevens et al. (2013)" ~ "24 Thai",
      Study == "Chen et al. (2016)" ~ "42 Mandarin",
      Study == "Bradley (2016)" ~ "26 Mandarin; 15 Yoruba",
      Study == "Wong et al. (2012)" ~ "408 Cantonese",
      Study == "Swaminathan et al (2021)" ~ "104 Chinese languages; 3 Vietnamese",
      Study == "Hove et al. (2010)" ~ "10 'Chinese'; 14 Hmong",
      Study == "Alexander et al. (2008)" ~ "14 Mandarin",
      Study == "Choi (2021)" ~ "30 Cantonese",
      Study == "Ngo et al. (2016)" ~ "8 Vietnamese",
      TRUE ~ Tonal
    ),
    `Non-tonal` = case_when(
      Study == "Peretz et al. (2011)" ~ "25 'non-tonal' (likely French/English)",
      Study == "Zheng \\& Samuel (2018)" ~ "24 English, 24 Korean",
      Study == "Stevens et al. (2013)" ~ "24 English",
      Study == "Chen et al. (2016)" ~ "42 Dutch",
      Study == "Bradley (2016)" ~ "26 English",
      Study == "Wong et al. (2012)" ~ "154 English/French",
      Study == "Swaminathan et al (2021)" ~ "366 English; 42 various non-tonal languages",
      Study == "Hove et al. (2010)" ~ "14 'Caucasian US students'",
      Study == "Alexander et al. (2008)" ~ "14 English",
      Study == "Choi (2021)" ~ "30 English",
      Study == "Ngo et al. (2016)" ~ "8 English",
      TRUE ~ `Non-tonal`
    )
  )

# meta_fig_assembler(melodic.gen.random, "melodic", "melodic_meta-plot.png", top_offset = 0.005, bottom_offset = -0.035, right_offset = -0.015)
```

```{r}
# MPT
pitch.gen.random$clean <- pitch.gen.random$data |>
  mutate( 
    Tonal = str_c(Tonal_N, " (", Non_CM_tonal, ")"), 
    `Non-tonal` = str_c(Non_tonal_N, " (", Non_E_nontonal, ")")
  ) |> 
  mutate(
    Study = case_when(
      `Non-tonal` == "11 (Portuguese, 1)" & Measure == "Interval discrimination" ~ "Pfordresher \\& Brown (2009), Study 2",
      `Non-tonal` == "11 (Portuguese, 1)" & Measure == "Note discrimination" ~ "Pfordresher \\& Brown (2009), Study 2",
      Study == "Pfordresher \\& Brown (2009)" & Measure == "Interval discrimination" ~ "Pfordresher \\& Brown (2009), Study 1",
      Study == "Pfordresher \\& Brown (2009)" ~ "Pfordresher \\& Brown (2009), Study 1",
      `Non-tonal` == "5 (No)" ~ "Bidelman et al. (2011), Study 2",
      Measure == "Mistuning detection (Study2)" ~ "Wong et al. (2012), Study 2",
      Measure == "Mistuned detection (Study1)" ~ "Wong et al. (2012), Study 1",
      TRUE ~ Study
    ),
    Measure = case_when(
      Measure == "Mistuning detection (Study2)" ~ "Mistuning detection",
      Measure == "Mistuned detection (Study1)" ~ "Mistuned detection",
      TRUE ~ Measure
    )
  ) |>
  mutate(
    Measure = if_else(Measure == "Interval discrimination/Musical Task", "Interval discrimination", Measure),
    Tonal = case_when(
      Study == "Peretz et al. (2011)" ~ "18 Mandarin; 4 Vietnamese; 2 Cantonese",
      Study == "Tong et al. (2018)" ~ "15 Cantonese",
      Study == "Pfordresher \\& Brown (2009), Study 1" ~ "6 Vietnamese; 4 Mandarin; 2 Cantonese",
      Study == "Pfordresher & Brown (2009), Study 2" ~ "11 Mandarin",
      Study == "Wong et al. (2012), Study 1" ~ "408 Cantonese",
      Study == "Wong et al. (2012), Study 2" ~ "22 Cantonese",
      Study == "Zheng \\& Samuel (2018)" ~ "24 Mandarin",
      Study == "Jasmin et al. (2021)" ~ "31 Cantonese",
      Study == "Giuliano et al. (2011), Study 1" ~ "17 Mandarin",
      Study == "Stevens et al. (2013)" ~ "24 Thai",
      Study == "Bidelman et al. (2011)" ~ "11 Mandarin",
      Study == "Tong et al. (2018)" ~ "30 Cantonese",
      Study == "Bent et al. (2006)"~ "13 Mandarin",
      Study == "Giuliano et al. (2011)" ~ "16 Mandarin",
      Study == "Hutka et al. (2015)" ~ "18 Cantonese",
      Study == "Bidelman et al. (2011), Study 2" ~ "5 Mandarin",
      Study == "Bidelman et al. (2013)" ~ "18 Cantonese",
      TRUE ~ paste0(Tonal_N, " ", Tonal_language)
    ),
    `Non-tonal` = case_when(
      Study == "Peretz et al. (2011)" ~ "25 'non-tonal' (likely French/English)",
      Study == "Tong et al. (2018)" ~ "15 English",
      Study == "Pfordresher \\& Brown (2009)" ~ "12 English",
      Study == "Pfordresher \\& Brown (2009), Study 2" ~ "10 English; 1 Portuguese",
      Study == "Wong et al. (2012), Study 1" ~ "154 English/French",
      Study == "Wong et al. (2012), Study 2" ~ "26 English/French",
      Study == "Jasmin et al. (2021)" ~ "36 English; 26 Spanish",
      Study == "Zheng \\& Samuel (2018)" ~ "24 English, 24 Korean",
      Study == "Giuliano et al. (2011), study 1" ~ "16 'Non-tonal'",
      Study == "Stevens et al. (2013)" ~ "24 English",
      Study == "Bidelman et al. (2011)" ~ "11 English",
      Study == "Tong et al. (2018)" ~ "11 English; 19 'Non-tonal'",
      Study == "Bent et al. (2006)"~ "13 English",
      Study == "Giuliano et al. (2011)" ~ "16 'Non-tonal'",
      Study == "Hutka et al. (2015)" ~ "21 English",
      Study == "Bidelman et al. (2011), Study 2" ~ "5 English",
      Study == "Bidelman et al. (2013)" ~ "18 English",
      TRUE ~ paste0(Non_tonal_N, " ", Comparison_language)
    )
  )

# fixing error with duplicate names by arbitrarily adding a number to the name
pitch.gen.random$studlab <- str_c(pitch.gen.random$studlab, 1:length(pitch.gen.random$studlab))

# meta_fig_assembler(pitch.gen.random, "pitch", "fine-pitch_meta-plot.png", top_offset = 0.028, bottom_offset = -0.016, right_offset = -0.015)
```

```{r}
# Beat processing
# MPT
rhythm.gen.random$clean <- rhythm.gen.random$data |>
  mutate( 
    Tonal = str_c(Tonal_N, " (", Non_CM_tonal, ")"), 
    `Non-tonal` = str_c(Non_tonal_N, " (", Non_E_nontonal, ")")
  ) |> 
    mutate(
    Study = case_when(
      Measure == "Off-beat detection (Study2)" ~ "Wong et al. (2012), Study 2",
      Measure == "Off-beat detection (Study1)" ~ "Wong et al. (2012), Study 1",
      TRUE ~ Study
    )
  ) |> 
  mutate(
    Measure = if_else(Measure == "Interval discrimination/Musical Task", "Interval discrimination", Measure),
    Tonal = case_when(
      Study == "Swaminathan et al (2021)" ~ "104 Chinese languages; 3 Vietnamese",
      Study == "Peretz et al. (2011)" ~ "18 Mandarin; 4 Vietnamese; 2 Cantonese",
      Study == "Wong et al. (2012), Study 1" ~ "408 Cantonese",
      Study == "Wong et al. (2012), Study 2" ~ "22 Cantonese",
      Study == "Ngo et al. (2016)" ~ "8 Vietnamese",
      Study == "Choi (2021)" ~ "30 Cantonese",
      Study == "Jasmin et al. (2021)" ~ "31 Mandarin",
      TRUE ~ Tonal
    ),
    `Non-tonal` = case_when(
      Study == "Swaminathan et al (2021)" ~ "366 English; 42 various non-tonal languages",
      Study == "Peretz et al. (2011)" ~ "25 'non-tonal' (likely French/English)",
      Study == "Wong et al. (2012), Study 1" ~ "154 English/French",
      Study == "Wong et al. (2012), Study 2" ~ "26 English",
      Study == "Ngo et al. (2016)" ~ "8 English",
      Study == "Choi (2021)" ~ "30 English",
      Study == "Jasmin et al. (2021)" ~ "62 English and Spanish",
      TRUE ~ `Non-tonal`
    )
  )

# meta_fig_assembler(rhythm.gen.random, "rhythm", "rhythm_meta-plot.png", top_offset = -0.04, bottom_offset = -0.07, right_offset = -0.015)

```


\clearpage
```{r Figure1, fig.height=4, fig.width=18, out.extra='angle=90'}


meta_fig_assembler2(melodic.gen.random, pitch.gen.random, rhythm.gen.random,
                    "meta-plot.pdf", top_offset = 0.07, bottom_offset = -0.02, right_offset = -0.015)

```


\clearpage

```{r FigureS2, fig.height=8, fig.width=12}

permutation_plot <- function(data, subtitle, fill_col, title = NULL) {
  ggplot(tibble(x = data$null), aes(x)) + 
    geom_histogram(colour = "black", fill = colorspace::lighten(fill_col, 0.9)) + 
    geom_vline(xintercept = data$actual, lty = "dotted", colour = "red") +
    annotate("text", x = data$actual + 0.002, y = 1100, label = paste("p =", data$p), hjust = 0) +
    labs(
      y = NULL,
      x = "Classification Accuracy",
      title = title,
      subtitle = subtitle
      ) +
    coord_cartesian(clip = "off") +
    theme_classic() + 
    theme(
      plot.title = element_text(hjust = 0.5, size = 15),
      plot.subtitle = element_text(hjust = 0.5),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank()
    )
}

wrap_plots(
  permutation_plot(permutation_tests$T_NT$mdt, "Melodic discrimination", "yellow"),
  permutation_plot(permutation_tests$T_NT$mpt, "Mistuning discrimination", "yellow", "Tonal vs non-tonal speakers"),
  permutation_plot(permutation_tests$T_NT$cabat, "Beat alignment", "yellow"),
  permutation_plot(permutation_tests$PA_NT$mdt, "Melodic discrimination", "blue"),
  permutation_plot(permutation_tests$PA_NT$mpt, "Mistuning discrimination", "blue", "Pitch-accent vs non-tonal speakers"),
  permutation_plot(permutation_tests$PA_NT$cabat, "Beat alignment", "blue"),
  ncol = 3
)

```
